name: movie_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  http: ^0.13.6
  material_symbols_icons: ^4.2668.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
